export default function PrivacyPolicyPage() {
  return (
    <div className="p-2 gap-2 flex flex-col text-sm">
      <h1 className="p-3 text-2xl font-bold">Privacy Policy</h1>
      <p>Last updated: May 8, 2024</p>
      <p>
        This Privacy Policy describes Our policies and procedures on the use of
        Your information when You use the Service and tells You about Your
        privacy rights.
      </p>

      <h2 className="p-3 text-xl font-bold">Interpretation and Definitions</h2>
      <h3 className="underline text-lg">Interpretation</h3>
      <p>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>

      <h3 className="underline text-lg">Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li>
          <p>
            <strong>Company</strong> (referred to as either &quot;the
            Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
            this Agreement) refers to Lil&quot; ToDo App.
          </p>
        </li>
        <li>
          <p>
            <strong>Cookies</strong> are small files that are placed on Your
            computer, mobile device or any other device by a website, containing
            the details of Your browsing history on that website among its many
            uses.
          </p>
        </li>
        <li>
          <p>
            <strong>Country</strong> refers to: Ukraine
          </p>
        </li>
        <li>
          <p>
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cellphone or a digital tablet.
          </p>
        </li>
        <li>
          <p>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </p>
        </li>
        <li>
          <p>
            <strong>Service</strong> refers to the Website.
          </p>
        </li>
        <li>
          <p>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </p>
        </li>
        <li>
          <p>
            <strong>Website</strong> refers to Lil&quot; ToDo App, accessible
            from
            <a
              href="https://lil-todo.vercel.app/"
              rel="external nofollow noopener"
              target="_blank"
            >
              {' '}
              https://lil-todo.vercel.app/
            </a>
          </p>
        </li>
        <li>
          <p>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </p>
        </li>
      </ul>

      <h2 className="p-3 text-xl font-bold">
        Collecting and Using Your Personal Data
      </h2>
      <h3 className="underline text-lg">Types of Data Collected</h3>
      <h4 className="ml-5">Personal Data</h4>
      <p>
        While using Our Service, We do not ask You to provide Us with certain
        personally identifiable information.
      </p>
      <h4 className="ml-5">Usage Data</h4>
      <p>Usage Data is not collected when using the Service.</p>

      <h4 className="ml-5">Tracking Technologies and Cookies</h4>
      <p>
        We do not use Cookies and similar tracking technologies to track the
        activity on Our Service and store certain information.
      </p>
      <p>
        <strong>Cookies or Browser Cookies.</strong> A cookie is a small file
        placed on Your Device. You can instruct Your browser to refuse all
        Cookies or to indicate when a Cookie is being sent.
      </p>

      <h2 className="p-3 text-xl font-bold">Children&apos;s Privacy</h2>
      <p>
        Our Service does not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 13. If You are a parent or guardian and You are aware that
        Your child has provided Us with Personal Data, please contact Us. If We
        become aware that We have collected Personal Data from anyone under the
        age of 13 without verification of parental consent, We take steps to
        remove that information from Our servers.
      </p>
      <p>
        If We need to rely on consent as a legal basis for processing Your
        information and Your country requires consent from a parent, We may
        require Your parent&apos;s consent before We collect and use that
        information.
      </p>

      <h2 className="p-3 text-xl font-bold">Links to Other Websites</h2>
      <p>
        Our Service does not contain links to other websites that are not
        operated by Us currently.
      </p>

      <h2 className="p-3 text-xl font-bold">Changes to this Privacy Policy</h2>
      <p>
        We may update Our Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page.
      </p>
      <p>
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on the top of this page.
      </p>

      <h2 className="p-3 text-xl font-bold">Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy, You may contact us:
      </p>
      <ul>
        <li>By email: aradkivska@gmail.com</li>
      </ul>
    </div>
  );
}
